export const MENU_FETCH_MENU = 'MENU/FETCH_MENU';
export const MENU_LOADED = 'MENU/LOADED';

export const MENU_ADD_MENU_BREAKFAST = 'MENU/ADD_MENU_BREAKFAST';
export const MENU_ADD_MENU_DINNER = 'MENU/ADD_MENU_DINNER';
export const MENU_ADD_MENU_SUPPER = 'MENU/ADD_MENU_SUPPER';

export const MENU_SET_MENU_BREAKFAST = 'MENU/SET_MENU_BREAKFAST';
export const MENU_SET_MENU_DINNER = 'MENU/SET_MENU_DINNER';
export const MENU_SET_MENU_SUPPER = 'MENU/SET_MENU_SUPPER';


export const MENU_DELETE_MENU_BREAKFAST = 'MENU/DELETE_MENU_BREAKFAST';
export const MENU_DELETE_MENU_DINNER = 'MENU/DELETE_MENU_DINNER';
export const MENU_DELETE_MENU_SUPPER = 'MENU/DELETE_MENU_SUPPER';

export const MENU_REMOVE_MENU_BREAKFAST = 'MENU/REMOVE_MENU_BREAKFAST';
export const MENU_REMOVE_MENU_DINNER = 'MENU/REMOVE_MENU_DINNER';
export const MENU_REMOVE_MENU_SUPPER = 'MENU/REMOVE_MENU_SUPPER';


